### ISSUE TITLE
[请教] 这个jekyllcn 可以用 jekyll serve 来自动生成吗？

### ISSUE THREAD

**Issue by archersmind** [xcatliu/jekyllcn#100]
初学者，请教一下这个 jekyllcn 可以用 `jekyll build` 或者 `jekyll serve` 来生成和预览吗？

**Comment by xcatliu** [comment]
[README.md](https://github.com/xcatliu/jekyllcn#如何在本地启动) 里面描述了如何启动：

> ## 如何在本地启动
>
> 1. 安装 [bundle](http://bundler.io/)
> 2. 执行 `bundle install`
> 3. 执行 `bundle exec rake site:preview`

**Comment by xcatliu** [comment]
使用 bundle 来启动是因为 [jekyll/site](https://github.com/jekyll/jekyll/tree/master/site) 是这样的，我就直接 fork 过来了，不过做了一些修改用来适应中文环境：

1. https://github.com/xcatliu/jekyllcn/commits/master/Rakefile
2. https://github.com/xcatliu/jekyllcn/commits/master/Gemfile

**Comment by xcatliu** [comment]
在国内的话，安装 bundle 可能会有问题，可以使用淘宝源：
https://ruby.taobao.org/

**Comment by archersmind** [comment]
Thanks

**Comment by ctfysh** [comment]
@xcatliu 执行 `bundle exec rake site:preview` 报错。

**Comment by xcatliu** [comment]
@ctfysh 请问报什么错呢？

**Comment by ctfysh** [comment]
![error](https://cloud.githubusercontent.com/assets/3131805/16325787/c455d4d8-39f3-11e6-9d13-bfe39d1ee324.jpg)
昨天上图失败了，不好意思啊。

**Comment by ctfysh** [comment]
@xcatliu 最近刚接触jekyll，正好看到有这个教程，对初学者很实用。
