### ISSUE TITLE
能加入你的github组织不？有翻译和校对经验，希望能做点贡献

### ISSUE THREAD

**Issue by CoderBOBO** [xcatliu/jekyllcn#113]

**Comment by xcatliu** [comment]
欢迎~
已加你为 Collaborator

**Comment by CoderBOBO** [comment]
@xcatliu 我这边咋没有提示？

**Comment by xcatliu** [comment]
@CoderBOBO jekyllcn 现在只是一个项目，不是一个组织。我把你加到 jekyllcn 的项目的 Collaborators 里面了。你看看能不能进入 [Settings 页面](https://github.com/xcatliu/jekyllcn/settings)？

**Comment by CoderBOBO** [comment]
哦哦，晓得了，我看了一下基本都翻译完了？

**Comment by xcatliu** [comment]
翻译基本完成了，但是是很久之前的翻译，官方版本更新过很多次，所以中文文档不一定是最新的。
如果有空的话，可以核对一下哪些还需要补充。

**Comment by CoderBOBO** [comment]
ok好的
