### ISSUE TITLE
[更新]已翻译内容

### ISSUE THREAD

**Issue by TimoTokki** [xcatliu/jekyllcn#115]
对比阅读发现，中文文档中有好些内容落后于官方版本。

**Comment by xcatliu** [comment]
感谢贡献！

**Comment by xcatliu** [comment]
可以把 README.md 里面的更新进度重新更新一下

**Comment by TimoTokki** [comment]
好嘞


From m1 metal

-------- Original message --------
Sender: Xcat Liu <notifications@github.com>
Time: Tue 4/19 11:34
To: xcatliu/jekyllcn <jekyllcn@noreply.github.com>
Cc: TimoTokki <wtbgcd84@163.com>
 Subject: Re: [xcatliu/jekyllcn] [更新]已翻译内容 (#115)
