### ISSUE TITLE
如何处理进度？

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/jekyllcn#129]
我们已经可以使用 [Travis CI](https://travis-ci.org/xcatliu/jekyllcn) 来自动化部署网页了。但是还是得手动修改 progress，这点很麻烦。

其实翻译基本已经完成了，只是有些文档还比较落后。所以现在的进度提示可能也不是很准确。

我提供一些想法：

1. 取消「翻译」和「更新」的区别，统一为最后更新时间。
2. 取消「进度」机制，`README.md` 不再显示当前进度。
3. 顶部公告栏不再显示当前进度，而改为一些更有意思的内容（比如主题搜集，博客搜集）。
4. 每篇文档显示最后更新时间，并欢迎用户协助更新。

**Comment by xcatliu** [comment]
好像主题搜集和博客搜集没什么必要，已经有其他站点在整理了
https://github.com/jekyll/jekyll/wiki/sites
https://github.com/jekyll/jekyll/wiki/Themes

**Comment by TimoTokki** [comment]
建议取消顶部公告栏，一方面更加贴近源网站风格；另外，顶栏的功能，我觉得，完全可以在其它地方实现。

比如，引导用户协助翻译，可以在每篇文档下方提供 [翻译链接](https://github.com/xcatliu/jekyllcn#如何贡献翻译)。

另外，建议，可以修改修改帮助栏下的内容，使其更符合国内使用环境，可以增加一些，比如主题搜集、博客搜集，或者如何修改镜像为淘宝源的教程之类的资源、链接。

**Comment by TimoTokki** [comment]
关于 Jekyll 主题搜集，还有一个不错的网站：[Jekyll Themes](http://jekyllthemes.org/)

**Comment by xcatliu** [comment]
同意「去掉顶部公告栏」

> 每篇文档提供翻译连接

这个应该已经实现了「发现错误或贡献翻译」就是的

**Comment by xcatliu** [comment]
分成几个独立的事情做吧

**Comment by TimoTokki** [comment]
我对 jekyllcn 的网站框架不太了解，有没有什么可以参考的文档？

**Comment by xcatliu** [comment]
@TimoTokki 本来是想写个文档的，后来发现改动太小了，就没写文档。你可以 `git diff jekyll/master` 看一下我们具体有哪些改动。

至于 jekyllrb 的网站的文档：https://github.com/jekyll/jekyll/tree/master/site

其实他也没啥文档……

> It's just a jekyll site, afterall! :wink:

**Comment by xcatliu** [comment]
已拆分任务，此 issue 关闭
