### ISSUE TITLE
fatal: jekyllrb/master - not something we can merge

### ISSUE THREAD

**Issue by baiyangcao** [xcatliu/jekyllcn#141]
- [x] jekyll 3.3.0
- [x] CentOS Linux release 7.2.1511 (Core)

I tried to follow the README to get the lastest jekyllrb

```
git remote add jekyllrb git@github.com:jekyll/jekyll.git
git fetch jekyllrb master
git merge jekyllrb/master
# 解决冲突
```

then I got the following error:

```
$ git remote add jekyllrb git@github.com:jekyll/jekyll.git
$ git fetch jekyllrb master
remote: Counting objects: 1421, done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 1421 (delta 597), reused 567 (delta 567), pack-reused 797
Receiving objects: 100% (1421/1421), 391.78 KiB | 522.00 KiB/s, done.
Resolving deltas: 100% (979/979), completed with 158 local objects.
From github.com:jekyll/jekyll
 * branch            master     -> FETCH_HEAD
$ git merge jekyllrb/master
fatal: jekyllrb/master - not something we can merge
```

**Comment by xcatliu** [comment]
Hi @baiyangcao 

I have no idea why it didn't work. It works fine on my machine.

Maybe you should try

```shell
git remote add jekyllrb git@github.com:jekyll/jekyll.git
git pull jekyllrb master
# 解决冲突
```

Checkout this for more information: http://stackoverflow.com/questions/12921125/git-merge-branch-of-another-remote

**Comment by xcatliu** [comment]
And a kind reminder, it will have a lot of conflicts need to be solved. Do it carefully 😆 

Thanks!

**Comment by baiyangcao** [comment]
Thanks for reply, I finally find the solution in your answer in the #122  
I use the following command:

```
git checkout master
git remote add jekyll git@github.com:jekyll/jekyll.git
git fetch --all
git checkout -b sync
git merge jekyll/master
git stataus
```

then I got the conflicts list, a lot~~~but I found the conflicts are the different languages, for example, I updated the translation of  windows.md in the last pull request, but the windows.md is still in the conflicts list, then I open the windows.md , finding the conflicts is the entire file, one is Chinese, another is the English one, so I'm confused what should I do with such kind of thing?

So I still compare the difference by the website pages and then update it manually~~

I really don't know how play with the `git merge` in such a translation project, I need a hand by hand tutorials for totally freshman... ...||>_<||

**Comment by xcatliu** [comment]
Thanks for your contribution!

Resolve conflicts is always a hard work...
For me, I just ignore all the English docs and then reset all the docs to JekyllCN:

```shell
git status
# A lot of conflicts
git checkout master site/_docs    # This will set all the docs to what they are in master branch
# Resolve other conflicts which are not translate issues
```

**Comment by baiyangcao** [comment]
话说，为毛两个中国人要用英语聊天，就因为这是个英文网站？？去他丫的吧，I am a Chinese. 都是我脑子抽了写了个英文issue

言归正传，直接把_docs重置成中文的话那不就不知道文档都有哪些有冲突，看不出来更新了？最后还是要眼动找更新的部分呗？

**Comment by xcatliu** [comment]
😆 练习说英文书写哈哈

> 言归正传，直接把_docs重置成中文的话那不就不知道文档都有哪些有冲突，看不出来更新了？最后还是要眼动找更新的部分呗？

是，翻译之后变化太大了，diff 功能无法识别段落的对应，只能人工识别。

你可能觉得直接重置的话，那么还 merge 干嘛，直接人工更新文档不就行了。

merge 到最新版本的目的是为了跟进官方的构建脚本，有时他们会添加一些新功能，时间太久不跟进就会越来越难 merge 了。

**Comment by baiyangcao** [comment]
那俺懂了，俺只要更新文档就行，反正脚本俺也看不懂~~~谢谢解答
