### ISSUE TITLE
网站关闭了？

### ISSUE THREAD

**Issue by zrzjohn** [xcatliu/jekyllcn#164]
为什么我访问网站的时候，显示的是这个样子？网站关闭了？
![网站关闭了？](view-source:https://preview.yozodcs.com/fcscloud/view/preview/H8_IEElJX0UZ2EhDzXI57daeipixmAn9HetuWas1cTibAIvI9bcvqoftvMWvJynMI4aF8RNNmyUGfsP1ltquUkQQEGb5-WqC1_AgQAA8kQHQCUHpUp8IUdLUsGO7HjcNhcslRuj0J-VsYQbiWNxSFFRCgxR21DtcyBDogkVqXD1rUPu_RxYK0TUVPi_douq6dfHw5t1s151iT_ylyp46QiPM-5z1I_yscDI-VilB-zi2fMcXcqJm7NruNrC8UK4-4hsiFLFRNMlSBdiGxNW8X_jr2rzGr8fXOHY2NWcv04Oaslz4Izpqk2akjd12y_d7c14QhGoi0xJxUnst1KHVuh7YaR1WGb74/QQ%E5%9B%BE%E7%89%8720200815140106.files/file0001.png)

**Comment by xcatliu** [comment]
没有关闭，由于部署在 github pages 上，有可能需要翻墙

**Comment by zrzjohn** [comment]
> 
> 
> 没有关闭，由于部署在 github pages 上，有可能需要翻墙

为什么我显示的是 AppServ 的自述页面？
