### ISSUE TITLE
更新到官方版本

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/jekyllcn#69]
构建方式改变了，需要在 README.md 中说明

**Comment by xcatliu** [comment]
已更新，改动如下：

- [x] 跟进官方网站版本（2015-06-22）
- [x] 首页中文适配（2015-06-22）
- [x] 页脚加上贡献翻译链接
- [x] 导航加上贡献翻译链接
- [x] 每篇文档加上贡献翻译链接
- [x] 加上 ga
- [x] 加上适配 jekyllcn 的 css
- [x] 加上如何贡献翻译的文档
- [x] 加上如何本地启动的文档
- [x] 加上项目进度的文档
- [x] header 中文适配
- [x] 上一节下一节中文适配
- [x] 右侧表头中文适配
- [x] head 中文适配
- [ ] 每篇文文档加上原文链接
- [x] 在 header 中加入贡献翻译链接
- [ ] 每篇文档加上翻译贡献者
- [x] 在 header 中底色代表项目进度

**Comment by chaucerling** [comment]
原文链接和翻译贡献者这样子可以吗？
![2015-06-22 20 38 13](https://cloud.githubusercontent.com/assets/6396793/8281881/b8cb0418-191e-11e5-9431-8fcacdccdd9b.png)

**Comment by xcatliu** [comment]
@chaucerling Nice!
提交一个 pull-request 吧~
