### ISSUE TITLE
更新 “开始” 栏目的文档

### ISSUE THREAD

**Issue by chaucerling** [xcatliu/jekyllcn#75]
翻译了前两个，我先提交一个 pull request，等全部翻译完你再 merge
另外之前翻译的是哪个版本的文档？人肉对比好难找到官方更新的地方，只能在 git 的 history 里一个个找

**Comment by xcatliu** [comment]
应该差不多是是 Apr 4, 2014 的版本，见 #61

**Comment by chaucerling** [comment]
要不在 YAML front matter 标注更新时候的官方的 version ，之后更新 diff 一下就知道要改哪些地方

**Comment by xcatliu** [comment]
可以加上 7 位的 hash 值即可。就叫 hash 字段？

**Comment by chaucerling** [comment]
恩
