### ISSUE TITLE
分页代码不对

### ISSUE THREAD

**Issue by insekkei** [xcatliu/jekyllcn#91]
http://jekyllcn.com/docs/pagination/的
“注意首尾页
Jekyll 没有生成文件夹 ‘page1’ ，所以上边的代码有 bug ，下边的代码解决了这个问题。”之后的代码粘贴过去依然找不到分页后的地址，而且样式很挫。
<img width="265" alt="qq20150902-1 2x" src="https://cloud.githubusercontent.com/assets/5036903/9622869/783fc3d6-516b-11e5-93e5-06c119f4eb65.png">
<img width="457" alt="qq20150902-2 2x" src="https://cloud.githubusercontent.com/assets/5036903/9622870/7886ad46-516b-11e5-9c9e-c55ba76ca453.png">

更新成http://jekyllrb.com/docs/pagination/
里“Beware the page one edge-case
Jekyll does not generate a ‘page1’ folder, so the above code will not work when a /page1 link is produced. See below for a way to handle this if it’s a problem for you.”
下方的代码就好了。
<img width="254" alt="qq20150902-3 2x" src="https://cloud.githubusercontent.com/assets/5036903/9622871/78c6b0d0-516b-11e5-9afd-b7ebaa253036.png">
<img width="494" alt="qq20150902-4 2x" src="https://cloud.githubusercontent.com/assets/5036903/9622874/79b94412-516b-11e5-9ea7-9dfc8d6a74c4.png">

**Comment by xcatliu** [comment]
site/_docs/pagination.md 需要更新
