### ISSUE TITLE
翻译 history

### ISSUE THREAD

**Issue by UniFreak** [xcatliu/jekyllcn#92]
顺便申请加入 collaborator 列表
虽然历史更新没多大意义, 但是看着就它没被翻译总心痒痒的

**Comment by xcatliu** [comment]
@UniFreak 抱歉没有及时处理，如果还有兴趣加入 collaborators，再告诉我一声吧~

**Comment by xcatliu** [comment]
History 不能直接更新，详见：#94

**Comment by xcatliu** [comment]
history 无法直接编辑，而且无法显示翻译者

鉴于 history 太多了，故放弃翻译
