### ISSUE TITLE
部署出现 bug

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/jekyllcn#94]
部署完成后会出现一个 not staged file:
```
modified:   site/_docs/history.md
```
并且此文件未部署成功

**Comment by xcatliu** [comment]
#93

**Comment by UniFreak** [comment]
不是很清楚部署的流程
但是如果是 not staged file, 是不是在部署之前应该先执行以下 git add history.md?

**Comment by xcatliu** [comment]
@UniFreak 恩，我有时间的时候再查查问题原因

**Comment by xcatliu** [comment]
@UniFreak 

已查出原因，是因为 [site/_docs/history.md](https://github.com/xcatliu/jekyllcn/blob/master/site/_docs/history.md) 是通过 [History.markdown](https://github.com/xcatliu/jekyllcn/blob/master/History.markdown) 生成的，详细代码：

https://github.com/xcatliu/jekyllcn/blob/master/Rakefile#L228-L246

我们需要直接更改 [History.markdown](https://github.com/xcatliu/jekyllcn/blob/master/History.markdown) 文件

**Comment by xcatliu** [comment]
更新，现在会额外多出一个 `site/_docs/contributing.md` unstaged file

**Comment by xcatliu** [comment]
已放弃翻译 history
